version: "3.7"
services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: './docker-configs/php-fpm'
    volumes:
      - ./src/:/var/phpapp/
      - ./docker-configs/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini