---
version: "3.7"
services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: './docker-configs/php-fpm'
      dockerfile: 'php.Dockerfile'
    volumes:
      - ${SRCDIR}:/var/www/src
      - ./docker-configs/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  composer:
    build:
      context: './docker-configs/composer'
      dockerfile: 'composer.Dockerfile'
    volumes:
      - ${SRCDIR}:/var/www/src
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "33306:3306"
    volumes:
      - ./docker-configs/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker-configs/mysql/data:/var/lib/mysql
      - ./docker-configs/mysql/my.cnf:/etc/init.d/mysql
