version: "3.7"
services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: './docker-configs/php-fpm'
    volumes:
      - ./src/:/var/phpapp/
      - ./docker-configs/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "33306:3306"
    volumes:
      - ./docker-configs/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker-configs/mysql/data:/var/lib/mysql
      - ./docker-configs/mysql/my.cnf:/etc/init.d/mysql